// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineApi.Models;

public partial class ButacasFuncione
{
    public int IdButaca { get; set; }

    public int IdFuncion { get; set; }

    public string Estado { get; set; }

    public virtual Butaca IdButacaNavigation { get; set; }

    public virtual Funcione IdFuncionNavigation { get; set; }
}