// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineApi.Models;

public partial class Comprobante
{
    public int IdComprobante { get; set; }

    public DateTime Fecha { get; set; }

    public int? IdCliente { get; set; }

    public int? IdFormaPago { get; set; }

    public int? IdFormaVenta { get; set; }

    public int? IdSucursal { get; set; }

    public virtual ICollection<DetComprobante> DetComprobantes { get; set; } = new List<DetComprobante>();

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual FormasPago IdFormaPagoNavigation { get; set; }

    public virtual FormasVentum IdFormaVentaNavigation { get; set; }

    public virtual Sucursale IdSucursalNavigation { get; set; }
}