// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineApi.Models;

public partial class Premio
{
    public int IdPremio { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Actore> IdActors { get; set; } = new List<Actore>();

    public virtual ICollection<Directore> IdDirectors { get; set; } = new List<Directore>();

    public virtual ICollection<Pelicula> IdPeliculas { get; set; } = new List<Pelicula>();
}