// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineApi.Models;

public partial class Ticket
{
    public int IdTicket { get; set; }

    public int? IdDetComprobante { get; set; }

    public int? IdButaca { get; set; }

    public virtual Butaca IdButacaNavigation { get; set; }

    public virtual DetComprobante IdDetComprobanteNavigation { get; set; }
}