// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineApi.Models;

public partial class Butaca
{
    public int IdButaca { get; set; }

    public int? IdSala { get; set; }

    public int Numero { get; set; }

    public string Fila { get; set; }

    public virtual ICollection<ButacasFuncione> ButacasFunciones { get; set; } = new List<ButacasFuncione>();

    public virtual Sala IdSalaNavigation { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}