// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineApi.Models;

public partial class DetComprobante
{
    public int IdDetComprobante { get; set; }

    public int? IdComprobante { get; set; }

    public int? IdFuncion { get; set; }

    public decimal? Descuento { get; set; }

    public int Cantidad { get; set; }

    public decimal Precio { get; set; }

    public virtual Comprobante IdComprobanteNavigation { get; set; }

    public virtual Funcione IdFuncionNavigation { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}