// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineApi.Models;

public partial class Funcione
{
    public int IdFuncion { get; set; }

    public int? IdPelicula { get; set; }

    public int? IdSala { get; set; }

    public DateTime? Dia { get; set; }

    public TimeSpan Horario { get; set; }

    public string Idioma { get; set; }

    public string TipoFuncion { get; set; }

    public virtual ICollection<ButacasFuncione> ButacasFunciones { get; set; } = new List<ButacasFuncione>();

    public virtual ICollection<DetComprobante> DetComprobantes { get; set; } = new List<DetComprobante>();

    public virtual Pelicula IdPeliculaNavigation { get; set; }

    public virtual Sala IdSalaNavigation { get; set; }
}