// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineApi.Models;

public partial class Promocione
{
    public int IdPromocion { get; set; }

    public string Nombre { get; set; }

    public DateTime? Dia { get; set; }

    public TimeSpan? HorarioFinalizacion { get; set; }

    public TimeSpan? HorarioInicio { get; set; }

    public decimal? Descuento { get; set; }

    public virtual ICollection<Sucursale> IdSucursals { get; set; } = new List<Sucursale>();
}