// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineApi.Models;

public partial class Sucursale
{
    public int IdSucursal { get; set; }

    public string NombreSucursal { get; set; }

    public string Direccion { get; set; }

    public int? IdBarrio { get; set; }

    public string Telefono { get; set; }

    public virtual ICollection<Comprobante> Comprobantes { get; set; } = new List<Comprobante>();

    public virtual Barrio IdBarrioNavigation { get; set; }

    public virtual ICollection<Sala> Salas { get; set; } = new List<Sala>();

    public virtual ICollection<Promocione> IdPromocions { get; set; } = new List<Promocione>();
}