// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tpi_Cine_Grupo12.Models;

public partial class Actores
{
    public int id_actor { get; set; }

    public string nombre { get; set; }

    public string apellido { get; set; }

    public DateOnly? fecha_nac { get; set; }

    public string nacionalidad { get; set; }

    public string biografia { get; set; }

    public virtual ICollection<Actores_premios> Actores_premios { get; set; } = new List<Actores_premios>();

    public virtual ICollection<Peliculas_actores> Peliculas_actores { get; set; } = new List<Peliculas_actores>();
}