// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tpi_Cine_Grupo12.Models;

public partial class Actores_premios
{
    public int id_actor_premio { get; set; }

    public int id_premio { get; set; }

    public int id_actor { get; set; }

    public virtual Actores id_actorNavigation { get; set; }

    public virtual Premios id_premioNavigation { get; set; }
}