// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tpi_Cine_Grupo12.Models;

public partial class Barrios
{
    public int id_barrio { get; set; }

    public string nombre_barrio { get; set; }

    public int? id_localidad { get; set; }

    public virtual ICollection<Sucursales> Sucursales { get; set; } = new List<Sucursales>();

    public virtual Localidades id_localidadNavigation { get; set; }
}