// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tpi_Cine_Grupo12.Models;

public partial class Butacas
{
    public int id_butaca { get; set; }

    public int? id_sala { get; set; }

    public int numero { get; set; }

    public string fila { get; set; }
    public string estado { get; set; } = "Disponible";

    public virtual ICollection<Butacas_funciones> Butacas_funciones { get; set; } = new List<Butacas_funciones>();

    public virtual ICollection<Tickets> Tickets { get; set; } = new List<Tickets>();

    public virtual Salas id_salaNavigation { get; set; }
}