// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tpi_Cine_Grupo12.Models;

public partial class Butacas_funciones
{
    public int id_butaca { get; set; }

    public int id_funcion { get; set; }

    public string estado { get; set; }

    public virtual Butacas id_butacaNavigation { get; set; }

    public virtual Funciones id_funcionNavigation { get; set; }
}