// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Tpi_Cine_Grupo12.Models;

public partial class CineDbContext : DbContext
{
    public CineDbContext(DbContextOptions<CineDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Actores> Actores { get; set; }

    public virtual DbSet<Actores_premios> Actores_premios { get; set; }

    public virtual DbSet<Barrios> Barrios { get; set; }

    public virtual DbSet<Butacas> Butacas { get; set; }

    public virtual DbSet<Butacas_funciones> Butacas_funciones { get; set; }

    public virtual DbSet<Clientes> Clientes { get; set; }

    public virtual DbSet<Comprobantes> Comprobantes { get; set; }

    public virtual DbSet<Det_Comprobante> Det_Comprobante { get; set; }

    public virtual DbSet<Directores> Directores { get; set; }

    public virtual DbSet<Directores_premios> Directores_premios { get; set; }

    public virtual DbSet<Formas_Pago> Formas_Pago { get; set; }

    public virtual DbSet<Formas_Venta> Formas_Venta { get; set; }

    public virtual DbSet<Funciones> Funciones { get; set; }

    public virtual DbSet<Generos> Generos { get; set; }

    public virtual DbSet<Localidades> Localidades { get; set; }

    public virtual DbSet<Peliculas> Peliculas { get; set; }

    public virtual DbSet<Peliculas_actores> Peliculas_actores { get; set; }

    public virtual DbSet<Peliculas_premios> Peliculas_premios { get; set; }

    public virtual DbSet<Premios> Premios { get; set; }

    public virtual DbSet<Promociones> Promociones { get; set; }

    public virtual DbSet<Promociones_sucursales> Promociones_sucursales { get; set; }

    public virtual DbSet<Provincias> Provincias { get; set; }

    public virtual DbSet<Salas> Salas { get; set; }

    public virtual DbSet<Sucursales> Sucursales { get; set; }

    public virtual DbSet<Tickets> Tickets { get; set; }

    public virtual DbSet<Tipos_salas> Tipos_salas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Actores>(entity =>
        {
            entity.HasKey(e => e.id_actor).HasName("PK__Actores__F86BE717A0080FDF");

            entity.Property(e => e.id_actor).ValueGeneratedNever();
            entity.Property(e => e.apellido)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.biografia)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.nacionalidad)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Actores_premios>(entity =>
        {
            entity.HasKey(e => e.id_actor_premio).HasName("PK__Actores___7B3112FF512511AE");

            entity.HasOne(d => d.id_actorNavigation).WithMany(p => p.Actores_premios)
                .HasForeignKey(d => d.id_actor)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Actores_p__id_ac__7B5B524B");

            entity.HasOne(d => d.id_premioNavigation).WithMany(p => p.Actores_premios)
                .HasForeignKey(d => d.id_premio)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Actores_p__id_pr__7A672E12");
        });

        modelBuilder.Entity<Barrios>(entity =>
        {
            entity.HasKey(e => e.id_barrio).HasName("pk_id_barrio");

            entity.Property(e => e.id_barrio).ValueGeneratedNever();
            entity.Property(e => e.nombre_barrio)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);

            entity.HasOne(d => d.id_localidadNavigation).WithMany(p => p.Barrios)
                .HasForeignKey(d => d.id_localidad)
                .HasConstraintName("fk_id_localidad");
        });

        modelBuilder.Entity<Butacas>(entity =>
        {
            entity.HasKey(e => e.id_butaca).HasName("PK__Butacas__EB757993687AB19E");

            entity.Property(e => e.id_butaca).ValueGeneratedNever();
            entity.Property(e => e.fila)
                .IsRequired()
                .HasMaxLength(5)
                .IsUnicode(false);

            entity.HasOne(d => d.id_salaNavigation).WithMany(p => p.Butacas)
                .HasForeignKey(d => d.id_sala)
                .HasConstraintName("FK__Butacas__id_sala__7D439ABD");
        });

        modelBuilder.Entity<Butacas_funciones>(entity =>
        {
            entity.HasKey(e => new { e.id_butaca, e.id_funcion }).HasName("PK__Butacas___64189F6F2DA7E779");

            entity.Property(e => e.estado)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.id_butacaNavigation).WithMany(p => p.Butacas_funciones)
                .HasForeignKey(d => d.id_butaca)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Butacas_f__id_bu__7E37BEF6");

            entity.HasOne(d => d.id_funcionNavigation).WithMany(p => p.Butacas_funciones)
                .HasForeignKey(d => d.id_funcion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Butacas_f__id_fu__7F2BE32F");
        });

        modelBuilder.Entity<Clientes>(entity =>
        {
            entity.HasKey(e => e.id_cliente).HasName("PK__Clientes__677F38F56696F98F");

            entity.HasIndex(e => e.email, "UQ__Clientes__AB6E61640E371A59").IsUnique();

            entity.Property(e => e.id_cliente).ValueGeneratedNever();
            entity.Property(e => e.apellido_cliente)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.contraseña)
                .HasMaxLength(40)
                .IsUnicode(false);
            entity.Property(e => e.email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.nombre_cliente)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.telefono)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.usuario)
                .HasMaxLength(25)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Comprobantes>(entity =>
        {
            entity.HasKey(e => e.id_comprobante).HasName("PK__Comproba__55E5E240F6A47C0A");

            entity.Property(e => e.estado)
                .HasMaxLength(100)
                .IsFixedLength();

            entity.HasOne(d => d.id_clienteNavigation).WithMany(p => p.Comprobantes)
                .HasForeignKey(d => d.id_cliente)
                .HasConstraintName("FK__Comproban__id_cl__00200768");

            entity.HasOne(d => d.id_forma_pagoNavigation).WithMany(p => p.Comprobantes)
                .HasForeignKey(d => d.id_forma_pago)
                .HasConstraintName("FK__Comproban__id_fo__01142BA1");

            entity.HasOne(d => d.id_forma_ventaNavigation).WithMany(p => p.Comprobantes)
                .HasForeignKey(d => d.id_forma_venta)
                .HasConstraintName("FK__Comproban__id_fo__02084FDA");

            entity.HasOne(d => d.id_sucursalNavigation).WithMany(p => p.Comprobantes)
                .HasForeignKey(d => d.id_sucursal)
                .HasConstraintName("FK__Comproban__id_su__02FC7413");
        });

        modelBuilder.Entity<Det_Comprobante>(entity =>
        {
            entity.HasKey(e => e.id_det_comprobante).HasName("PK__Det_Comp__FC2F3668E3AD84D5");

            entity.Property(e => e.descuento).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.precio).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.id_comprobanteNavigation).WithMany(p => p.Det_Comprobante)
                .HasForeignKey(d => d.id_comprobante)
                .HasConstraintName("FK__Det_Compr__id_co__03F0984C");

            entity.HasOne(d => d.id_funcionNavigation).WithMany(p => p.Det_Comprobante)
                .HasForeignKey(d => d.id_funcion)
                .HasConstraintName("FK__Det_Compr__id_fu__04E4BC85");
        });

        modelBuilder.Entity<Directores>(entity =>
        {
            entity.HasKey(e => e.id_director).HasName("PK__Director__6B65E2A22ACF0838");

            entity.Property(e => e.id_director).ValueGeneratedNever();
            entity.Property(e => e.apellido)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.biografia)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.nacionalidad)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Directores_premios>(entity =>
        {
            entity.HasKey(e => new { e.id_premio, e.id_director }).HasName("PK__Director__9F3F196F3444EF87");

            entity.Property(e => e.id_director_premio).ValueGeneratedOnAdd();

            entity.HasOne(d => d.id_directorNavigation).WithMany(p => p.Directores_premios)
                .HasForeignKey(d => d.id_director)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Directore__id_di__06CD04F7");

            entity.HasOne(d => d.id_premioNavigation).WithMany(p => p.Directores_premios)
                .HasForeignKey(d => d.id_premio)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Directore__id_pr__05D8E0BE");
        });

        modelBuilder.Entity<Formas_Pago>(entity =>
        {
            entity.HasKey(e => e.id_forma_pago).HasName("PK__Formas_P__DA9B39EE4C1E1062");

            entity.Property(e => e.id_forma_pago).ValueGeneratedNever();
            entity.Property(e => e.descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Formas_Venta>(entity =>
        {
            entity.HasKey(e => e.id_forma_venta).HasName("PK__Formas_V__FD82D6217C27A313");

            entity.Property(e => e.id_forma_venta).ValueGeneratedNever();
            entity.Property(e => e.descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Funciones>(entity =>
        {
            entity.HasKey(e => e.id_funcion).HasName("PK__Funcione__F6DE6FC9E46801EF");

            entity.Property(e => e.idioma)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.tipo_funcion)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.id_peliculaNavigation).WithMany(p => p.Funciones)
                .HasForeignKey(d => d.id_pelicula)
                .HasConstraintName("FK__Funciones__id_pe__07C12930");

            entity.HasOne(d => d.id_salaNavigation).WithMany(p => p.Funciones)
                .HasForeignKey(d => d.id_sala)
                .HasConstraintName("FK__Funciones__id_sa__08B54D69");
        });

        modelBuilder.Entity<Generos>(entity =>
        {
            entity.HasKey(e => e.id_genero).HasName("PK__Generos__99A8E4F9A6499944");

            entity.Property(e => e.id_genero).ValueGeneratedNever();
            entity.Property(e => e.descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Localidades>(entity =>
        {
            entity.HasKey(e => e.id_localidad).HasName("pk_id_localidad");

            entity.Property(e => e.id_localidad).ValueGeneratedNever();
            entity.Property(e => e.nombre_localidad)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);

            entity.HasOne(d => d.id_provinciaNavigation).WithMany(p => p.Localidades)
                .HasForeignKey(d => d.id_provincia)
                .HasConstraintName("fk_id_provincia");
        });

        modelBuilder.Entity<Peliculas>(entity =>
        {
            entity.HasKey(e => e.id_pelicula).HasName("PK__Pelicula__B5017F4DECEA77A3");

            entity.Property(e => e.clasificacion)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.titulo)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.id_directorNavigation).WithMany(p => p.Peliculas)
                .HasForeignKey(d => d.id_director)
                .HasConstraintName("FK__Peliculas__id_di__0A9D95DB");

            entity.HasOne(d => d.id_generoNavigation).WithMany(p => p.Peliculas)
                .HasForeignKey(d => d.id_genero)
                .HasConstraintName("FK__Peliculas__id_ge__0B91BA14");
        });

        modelBuilder.Entity<Peliculas_actores>(entity =>
        {
            entity.HasKey(e => new { e.id_actor, e.id_pelicula }).HasName("PK__Pelicula__333BF0E3DB8962CD");

            entity.Property(e => e.id_peliculas_actores).ValueGeneratedOnAdd();

            entity.HasOne(d => d.id_actorNavigation).WithMany(p => p.Peliculas_actores)
                .HasForeignKey(d => d.id_actor)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Peliculas__id_ac__0C85DE4D");

            entity.HasOne(d => d.id_peliculaNavigation).WithMany(p => p.Peliculas_actores)
                .HasForeignKey(d => d.id_pelicula)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Peliculas__id_pe__0D7A0286");
        });

        modelBuilder.Entity<Peliculas_premios>(entity =>
        {
            entity.HasKey(e => new { e.id_premio, e.id_pelicula }).HasName("PK__Pelicula__62D950B186062E56");

            entity.Property(e => e.id_pelicula_premio).ValueGeneratedOnAdd();

            entity.HasOne(d => d.id_peliculaNavigation).WithMany(p => p.Peliculas_premios)
                .HasForeignKey(d => d.id_pelicula)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Peliculas__id_pe__0F624AF8");

            entity.HasOne(d => d.id_premioNavigation).WithMany(p => p.Peliculas_premios)
                .HasForeignKey(d => d.id_premio)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Peliculas__id_pr__0E6E26BF");
        });

        modelBuilder.Entity<Premios>(entity =>
        {
            entity.HasKey(e => e.id_premio).HasName("PK__Premios__A989474509BC5686");

            entity.Property(e => e.id_premio).ValueGeneratedNever();
            entity.Property(e => e.descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Promociones>(entity =>
        {
            entity.HasKey(e => e.id_promocion).HasName("PK__Promocio__F89308E012342EA8");

            entity.Property(e => e.id_promocion).ValueGeneratedNever();
            entity.Property(e => e.descuento).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Promociones_sucursales>(entity =>
        {
            entity.HasKey(e => new { e.id_promocion, e.id_sucursal }).HasName("PK__Promocio__DC5450E1A03C7C69");

            entity.Property(e => e.id_promocion_sucursal).ValueGeneratedOnAdd();

            entity.HasOne(d => d.id_promocionNavigation).WithMany(p => p.Promociones_sucursales)
                .HasForeignKey(d => d.id_promocion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Promocion__id_pr__10566F31");

            entity.HasOne(d => d.id_sucursalNavigation).WithMany(p => p.Promociones_sucursales)
                .HasForeignKey(d => d.id_sucursal)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Promocion__id_su__114A936A");
        });

        modelBuilder.Entity<Provincias>(entity =>
        {
            entity.HasKey(e => e.id_provincia).HasName("pk_id_provincia");

            entity.Property(e => e.id_provincia).ValueGeneratedNever();
            entity.Property(e => e.nombre_provincia)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Salas>(entity =>
        {
            entity.HasKey(e => e.id_sala).HasName("PK__Salas__D18B015B2B13831B");

            entity.Property(e => e.id_sala).ValueGeneratedNever();
            entity.Property(e => e.nombre)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.id_sucursalNavigation).WithMany(p => p.Salas)
                .HasForeignKey(d => d.id_sucursal)
                .HasConstraintName("FK__Salas__id_sucurs__123EB7A3");

            entity.HasOne(d => d.id_tipo_salaNavigation).WithMany(p => p.Salas)
                .HasForeignKey(d => d.id_tipo_sala)
                .HasConstraintName("FK__Salas__id_tipo_s__1332DBDC");
        });

        modelBuilder.Entity<Sucursales>(entity =>
        {
            entity.HasKey(e => e.id_sucursal).HasName("PK__Sucursal__4C75801359F901D7");

            entity.Property(e => e.direccion)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.nombre_sucursal)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.telefono)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.id_barrioNavigation).WithMany(p => p.Sucursales)
                .HasForeignKey(d => d.id_barrio)
                .HasConstraintName("fk_id_barrio");
        });

        modelBuilder.Entity<Tickets>(entity =>
        {
            entity.HasKey(e => e.id_ticket).HasName("PK__Tickets__48C6F5233C3CBF6E");

            entity.Property(e => e.id_ticket).ValueGeneratedNever();

            entity.HasOne(d => d.id_butacaNavigation).WithMany(p => p.Tickets)
                .HasForeignKey(d => d.id_butaca)
                .HasConstraintName("FK__Tickets__id_buta__151B244E");

            entity.HasOne(d => d.id_det_comprobanteNavigation).WithMany(p => p.Tickets)
                .HasForeignKey(d => d.id_det_comprobante)
                .HasConstraintName("FK__Tickets__id_det___160F4887");
        });

        modelBuilder.Entity<Tipos_salas>(entity =>
        {
            entity.HasKey(e => e.id_tipo_sala).HasName("PK__Tipos_sa__1C51F013B7D1A2EF");

            entity.Property(e => e.id_tipo_sala).ValueGeneratedNever();
            entity.Property(e => e.descripcion)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}