// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Tpi_Cine_Grupo12.Models;

public partial class Clientes
{
    public int id_cliente { get; set; }

    public string nombre_cliente { get; set; }

    public string apellido_cliente { get; set; }

    public string email { get; set; }

    public string telefono { get; set; }

    public string usuario { get; set; }

    public string contraseña { get; set; }

    public virtual ICollection<Comprobantes> Comprobantes { get; set; } = new List<Comprobantes>();
}