// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tpi_Cine_Grupo12.Models;

public partial class Comprobantes
{
    public int id_comprobante { get; set; }

    public DateOnly fecha { get; set; }

    public int? id_cliente { get; set; }

    public int? id_forma_pago { get; set; }

    public int? id_forma_venta { get; set; }

    public int? id_sucursal { get; set; }

    public string estado { get; set; }

    public virtual ICollection<Det_Comprobante> Det_Comprobante { get; set; } = new List<Det_Comprobante>();

    public virtual Clientes id_clienteNavigation { get; set; }

    public virtual Formas_Pago id_forma_pagoNavigation { get; set; }

    public virtual Formas_Venta id_forma_ventaNavigation { get; set; }

    public virtual Sucursales id_sucursalNavigation { get; set; }
}