// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tpi_Cine_Grupo12.Models;

public partial class Det_Comprobante
{
    public int id_det_comprobante { get; set; }

    public int? id_comprobante { get; set; }

    public int? id_funcion { get; set; }

    public decimal? descuento { get; set; }

    public int cantidad { get; set; }

    public decimal precio { get; set; }

    public virtual ICollection<Tickets> Tickets { get; set; } = new List<Tickets>();

    public virtual Comprobantes id_comprobanteNavigation { get; set; }

    public virtual Funciones id_funcionNavigation { get; set; }
}