// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tpi_Cine_Grupo12.Models;

public partial class Directores
{
    public int id_director { get; set; }

    public string nombre { get; set; }

    public string apellido { get; set; }

    public DateOnly? fecha_nac { get; set; }

    public string nacionalidad { get; set; }

    public string biografia { get; set; }

    public virtual ICollection<Directores_premios> Directores_premios { get; set; } = new List<Directores_premios>();

    public virtual ICollection<Peliculas> Peliculas { get; set; } = new List<Peliculas>();
}