// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tpi_Cine_Grupo12.Models;

public partial class Directores_premios
{
    public int id_director_premio { get; set; }

    public int id_premio { get; set; }

    public int id_director { get; set; }

    public virtual Directores id_directorNavigation { get; set; }

    public virtual Premios id_premioNavigation { get; set; }
}