// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tpi_Cine_Grupo12.Models;

public partial class Formas_Venta
{
    public int id_forma_venta { get; set; }

    public string descripcion { get; set; }

    public virtual ICollection<Comprobantes> Comprobantes { get; set; } = new List<Comprobantes>();
}