// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tpi_Cine_Grupo12.Models;

public partial class Funciones
{
    public int id_funcion { get; set; }

    public int? id_pelicula { get; set; }

    public int? id_sala { get; set; }

    public DateOnly? dia { get; set; }

    public TimeOnly horario { get; set; }

    public string idioma { get; set; }

    public string tipo_funcion { get; set; }

    public virtual ICollection<Butacas_funciones> Butacas_funciones { get; set; } = new List<Butacas_funciones>();

    public virtual ICollection<Det_Comprobante> Det_Comprobante { get; set; } = new List<Det_Comprobante>();

    public virtual Peliculas id_peliculaNavigation { get; set; }

    public virtual Salas id_salaNavigation { get; set; }
}