// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tpi_Cine_Grupo12.Models;

public partial class Generos
{
    public int id_genero { get; set; }

    public string descripcion { get; set; }

    public virtual ICollection<Peliculas> Peliculas { get; set; } = new List<Peliculas>();
}