// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tpi_Cine_Grupo12.Models;

public partial class Localidades
{
    public int id_localidad { get; set; }

    public string nombre_localidad { get; set; }

    public int? id_provincia { get; set; }

    public virtual ICollection<Barrios> Barrios { get; set; } = new List<Barrios>();

    public virtual Provincias id_provinciaNavigation { get; set; }
}