// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tpi_Cine_Grupo12.Models;

public partial class Peliculas_actores
{
    public int id_peliculas_actores { get; set; }

    public int id_actor { get; set; }

    public int id_pelicula { get; set; }

    public virtual Actores id_actorNavigation { get; set; }

    public virtual Peliculas id_peliculaNavigation { get; set; }
}