// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tpi_Cine_Grupo12.Models;

public partial class Peliculas
{
    public int id_pelicula { get; set; }

    public string titulo { get; set; }

    public int duracion { get; set; }

    public int? id_genero { get; set; }

    public int? id_director { get; set; }

    public int? anio_lanzamiento { get; set; }

    public DateOnly? fecha_estreno { get; set; }

    public string clasificacion { get; set; }

    public virtual ICollection<Funciones> Funciones { get; set; } = new List<Funciones>();

    public virtual ICollection<Peliculas_actores> Peliculas_actores { get; set; } = new List<Peliculas_actores>();

    public virtual ICollection<Peliculas_premios> Peliculas_premios { get; set; } = new List<Peliculas_premios>();

    public virtual Directores id_directorNavigation { get; set; }

    public virtual Generos id_generoNavigation { get; set; }
}