// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tpi_Cine_Grupo12.Models;

public partial class Peliculas_premios
{
    public int id_pelicula_premio { get; set; }

    public int id_premio { get; set; }

    public int id_pelicula { get; set; }

    public virtual Peliculas id_peliculaNavigation { get; set; }

    public virtual Premios id_premioNavigation { get; set; }
}