// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tpi_Cine_Grupo12.Models;

public partial class Premios
{
    public int id_premio { get; set; }

    public string descripcion { get; set; }

    public virtual ICollection<Actores_premios> Actores_premios { get; set; } = new List<Actores_premios>();

    public virtual ICollection<Directores_premios> Directores_premios { get; set; } = new List<Directores_premios>();

    public virtual ICollection<Peliculas_premios> Peliculas_premios { get; set; } = new List<Peliculas_premios>();
}