// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tpi_Cine_Grupo12.Models;

public partial class Promociones
{
    public int id_promocion { get; set; }

    public string nombre { get; set; }

    public DateOnly? dia { get; set; }

    public TimeOnly? horario_finalizacion { get; set; }

    public TimeOnly? horario_inicio { get; set; }

    public decimal? descuento { get; set; }

    public virtual ICollection<Promociones_sucursales> Promociones_sucursales { get; set; } = new List<Promociones_sucursales>();
}