// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tpi_Cine_Grupo12.Models;

public partial class Promociones_sucursales
{
    public int id_promocion_sucursal { get; set; }

    public int id_promocion { get; set; }

    public int id_sucursal { get; set; }

    public virtual Promociones id_promocionNavigation { get; set; }

    public virtual Sucursales id_sucursalNavigation { get; set; }
}