// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tpi_Cine_Grupo12.Models;

public partial class Provincias
{
    public int id_provincia { get; set; }

    public string nombre_provincia { get; set; }

    public virtual ICollection<Localidades> Localidades { get; set; } = new List<Localidades>();
}