// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tpi_Cine_Grupo12.Models;

public partial class Salas
{
    public int id_sala { get; set; }

    public string nombre { get; set; }

    public int? id_tipo_sala { get; set; }

    public int capacidad { get; set; }

    public int? id_sucursal { get; set; }

    public virtual ICollection<Butacas> Butacas { get; set; } = new List<Butacas>();

    public virtual ICollection<Funciones> Funciones { get; set; } = new List<Funciones>();

    public virtual Sucursales id_sucursalNavigation { get; set; }

    public virtual Tipos_salas id_tipo_salaNavigation { get; set; }
}