// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tpi_Cine_Grupo12.Models;

public partial class Sucursales
{
    public int id_sucursal { get; set; }

    public string nombre_sucursal { get; set; }

    public string direccion { get; set; }

    public int? id_barrio { get; set; }

    public string telefono { get; set; }

    public virtual ICollection<Comprobantes> Comprobantes { get; set; } = new List<Comprobantes>();

    public virtual ICollection<Promociones_sucursales> Promociones_sucursales { get; set; } = new List<Promociones_sucursales>();

    public virtual ICollection<Salas> Salas { get; set; } = new List<Salas>();

    public virtual Barrios id_barrioNavigation { get; set; }
}