// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tpi_Cine_Grupo12.Models;

public partial class Tickets
{
    public int id_ticket { get; set; }

    public int? id_det_comprobante { get; set; }

    public int? id_butaca { get; set; }

    public virtual Butacas id_butacaNavigation { get; set; }

    public virtual Det_Comprobante id_det_comprobanteNavigation { get; set; }
}