// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tpi_Cine_Grupo12.Models;

public partial class Tipos_salas
{
    public int id_tipo_sala { get; set; }

    public string descripcion { get; set; }

    public virtual ICollection<Salas> Salas { get; set; } = new List<Salas>();
}